### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by getpinga** [aoware/slim-saas-boilerplate#1]
Hi,
What is the license of this project?

Thank you.

**Comment by aoware** [comment]
Hi,

License is MIT
https://github.com/aoware/slim-saas-boilerplate/blob/main/LICENSE.md

Best regards,

Alain

On 31/01/2023 13:56, Pinga wrote:

> Hi,
> What is the license of this project?
> 
> Thank you.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you are subscribed to this 
> thread.Message ID: ***@***.***>


Links:
------
[1] https://github.com/aoware/slim-saas-boilerplate/issues/1
[2]

**Comment by getpinga** [comment]
Thank you,
Alain

I was looking for such project. I will make a fork where I'll add things like Swoole, Plates templating,  more mailing and SMS options and once I'm ready, will submit PRs back in case you are interested.

Kind regards,
Taras

**Comment by aoware** [comment]
Feel free to fork.

It is only the beginning of this project as I need to produce at least 2 
saas out of it in the coming month.
Mailing is implemented through smtp already.
Templating is done by Twig, so unsure we would ever use Plates.
SMS options would definitely be welcome.
Enjoy.

On 31/01/2023 14:23, Pinga wrote:

> Thank you,
> Alain
> 
> I was looking for such project. I will make a fork where I'll add 
> things like Swoole, Plates templating, more mailing and SMS options and 
> once I'm ready, will submit PRs back in case you are interested.
> 
> Kind regards,
> Taras
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you commented.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/aoware/slim-saas-boilerplate/issues/1#issuecomment-1410447504
[2]
